server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gland?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  mvc:
    view:
      prefix: classpath:/webapp/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/webapp/

  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username: 568331921@qq.com
    password: qsijqjvhmopmbdbi
    default-encoding: UTF-8


mybatis-plus:
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

