server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gland?characterEncoding=utf8&useSSL=false
    username: root
    password: root

    #url: jdbc:mysql://127.0.0.1:3306/gland?characterEncoding=utf8&useSSL=false
    #username: gland
    #password: ed306Lpj

  mvc:
    view:
      prefix: classpath:/webapp/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/webapp/

  thymeleaf:
    cache: true
    mode: HTML
    encoding: utf-8
    enabled: true
    prefix: /
    suffix: .html

  mail:
    host: smtp.qq.com
    username: 568331921@qq.com
    password: qsijqjvhmopmbdbi
    default-encoding: UTF-8
    sendTo: lisiqi@spic.com.cn


mybatis-plus:
  configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

